# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gali < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/srz-zumix/gali/releases/download/v0.2.0/gali_Darwin_x86_64.tar.gz"
      sha256 "8e42c7e955da5cd8704ebf89fd4d2161b688cab0b10fb08ba93cea1f1c2443cc"

      define_method(:install) do
        bin.install "gali"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/srz-zumix/gali/releases/download/v0.2.0/gali_Darwin_arm64.tar.gz"
      sha256 "c07b3974bec370058b89327b37d921b70d785b094bc009b903566e5a59aa8e9b"

      define_method(:install) do
        bin.install "gali"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/srz-zumix/gali/releases/download/v0.2.0/gali_Linux_x86_64.tar.gz"
      sha256 "938a608d269d12187c7e927b254aba7f114cbe91e73182096bc0057e7f369f11"
      define_method(:install) do
        bin.install "gali"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/srz-zumix/gali/releases/download/v0.2.0/gali_Linux_arm64.tar.gz"
      sha256 "7c29363d8bfd845e664c6c2265b92eefa12ca6a9875662c9edd110d3650d0dc6"
      define_method(:install) do
        bin.install "gali"
      end
    end
  end
end
