# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gali < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/srz-zumix/gali/releases/download/v0.1.1/gali_Darwin_x86_64.tar.gz"
      sha256 "894ca9225ea4297a3bcd3bc85f41d0abb20b57ba9f49cd7311c2f1d074a04b3d"

      def install
        bin.install "gali"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/srz-zumix/gali/releases/download/v0.1.1/gali_Darwin_arm64.tar.gz"
      sha256 "29e106dfadb19dbe389c5455d0da84d945891377a9f1ae979b7df6465f34cf5d"

      def install
        bin.install "gali"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/srz-zumix/gali/releases/download/v0.1.1/gali_Linux_x86_64.tar.gz"
      sha256 "6de0ad998b4759604058b4cf10bc0dd3cecf7a40b595248ad478c4d817df8583"
      def install
        bin.install "gali"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/srz-zumix/gali/releases/download/v0.1.1/gali_Linux_arm64.tar.gz"
      sha256 "ffb566d16185aa6eec437b5bfc7905713132cc41fd2ffb9771b79241848ca296"
      def install
        bin.install "gali"
      end
    end
  end
end
