# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoGitUseCommitTimes < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/srz-zumix/go-git-use-commit-times/releases/download/v0.2.0/go-git-use-commit-times_Darwin_x86_64.tar.gz"
      sha256 "a0af650530c5369f372369cfcdedc5b7983caf482bd33ef2246ece7ce2cfa439"

      def install
        bin.install "git-use-commit-times"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/srz-zumix/go-git-use-commit-times/releases/download/v0.2.0/go-git-use-commit-times_Darwin_arm64.tar.gz"
      sha256 "1f5467c884b6413edc08d95359842c0bc1f49179cd1588aabb90b2b7c4cce826"

      def install
        bin.install "git-use-commit-times"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/srz-zumix/go-git-use-commit-times/releases/download/v0.2.0/go-git-use-commit-times_Linux_x86_64.tar.gz"
      sha256 "65f6188f634f67506e247c8c61438cae7b4992c70a2fd34f8ab6f126aff643c1"
      def install
        bin.install "git-use-commit-times"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/srz-zumix/go-git-use-commit-times/releases/download/v0.2.0/go-git-use-commit-times_Linux_arm64.tar.gz"
      sha256 "de43e878f6358b639409979f42ae44f31e97fa3f4eac2d87c2391bbe368a1445"
      def install
        bin.install "git-use-commit-times"
      end
    end
  end
end
